### PR TITLE
chore: Remove signature overloading

### PR DESCRIPTION
**Pull request by claudiachua**
Internal JIRA Link: [DI-2426](https://issues.corp.twilio.com/browse/DI-2426)
Generated Changes: https://github.com/twilio/twilio-node/pull/872

Note: After reviewing the implementation of `getPage` function - it seems that `targetURL` param should not be [optional](https://github.com/twilio/twilio-oai-generator/compare/DI-2426?expand=1#diff-50a1a7176926062c86656e7b74b530ddd9208cc23a4b8bee9efe3ef834060386R62)

### CODE REVIEW

**Comment by childish-sambino** [comment]
Node tests are failing.

**Review by childish-sambino — APPROVED** [review]

**Comment by childish-sambino** [comment]
tsc is failing in examples.

**Comment by claudiachua** [comment]
@childish-sambino It's weird how tsc throws error only on `fleet.ts`, it's the same issue (in twilio-node) previously where `params` is `(option | function)` but `callback` is just `function`. [`as (error: Error| null, items) => any`](https://github.com/twilio/twilio-node/pull/872#discussion_r1061970690) was used to solve it previously.

**Comment by childish-sambino** [comment]
Really strange. Not sure why it works in some cases but not in others. See if changing the if check to this helps
```js
    if (params instanceof Function) {
      callback = params;
```

**Comment by childish-sambino** [comment]
Relates to https://github.com/microsoft/TypeScript/issues/37663#issuecomment-759728342

**Pull request merged**
