### PR TITLE
chore: Updated Page module imports and references

### PR DESCRIPTION
**Pull request by Hunga1**
Updated Page module imports and references with the removal of the Page namespace.

Supports changes made to the Page module in https://github.com/twilio/twilio-node/pull/840

### CODE REVIEW

**Review by childish-sambino — APPROVED** [review]
Need to re-generate the node examples. E.g., `make generate LANGUAGES=node`

**Review by claudiachua — APPROVED** [review]

**Review by claudiachua — COMMENTED** [review]
Should also open a twilio-node PR (for 4.0.0-rc) to view the full generated changes and include the link here

**Comment by beebzz** [comment]
> Should also open a twilio-node PR (for 4.0.0-rc) to view the full generated changes and include the link here

+1

**Comment by Hunga1** [comment]
Generated code changes in twilio-node:
https://github.com/twilio/twilio-node/pull/841

**Review by JenniferMah — APPROVED** [review]

**Pull request merged**
