### PR TITLE
test: split out sonar scanning into monorepo projects

### PR DESCRIPTION
**Pull request by childish-sambino**
Also add support for generating/testing only certain languages: `make generate LANGUAGES="php java"`

### CODE REVIEW

**Review by mattcole19 — APPROVED** [review]
Noice - this is much needed!

**Comment by mattcole19** [comment]
Can we extend this to test-docker? Think we could do it by only setting [LANGUAGES](https://github.com/twilio/twilio-oai-generator/blob/main/scripts/prism.sh#L4) if it is empty:

if LANGUAGES is empty:
   LANGUAGES = all langs

**Comment by childish-sambino** [comment]
@mattcole19 Already done: https://github.com/twilio/twilio-oai-generator/blob/957f4767c2eb5758831cdfb37f28c7c77e720269/scripts/prism.sh#L4-L8

**Comment by mattcole19** [comment]
> @mattcole19 Already done:
> 
> https://github.com/twilio/twilio-oai-generator/blob/957f4767c2eb5758831cdfb37f28c7c77e720269/scripts/prism.sh#L4-L8

Bash syntax will forever confuse me

**Pull request merged**
