### PR TITLE
fix: array type template

### PR DESCRIPTION
**Pull request by shamigor**
# Fixes #

A short description of what this PR does.

### Checklist
- [x] I acknowledge that all my contributions will be made under the project's license
- [x] Run `make test-docker`
- [x] Verify affected language:
    - [x] Generate [twilio-go](https://github.com/twilio/twilio-go) from our [OpenAPI specification](https://github.com/twilio/twilio-oai) using the [build_twilio_go.py](./examples/build_twilio_go.py) using `python examples/build_twilio_go.py path/to/twilio-oai/spec/yaml path/to/twilio-go` and inspect the diff
    - [x] Run `make test` in `twilio-go`
    - [x] Create a pull request in `twilio-go`
    - [x] Provide a link below to the pull request
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guidelines](https://github.com/twilio/twilio-oai-generator/blob/main/CONTRIBUTING.md) and my PR follows them
- [x] I have titled the PR appropriately
- [x] I have updated my branch with the main branch
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added the necessary documentation about the functionality in the appropriate .md file
- [ ] I have added inline documentation to the code I modified

If you have questions, please create a GitHub Issue in this repository.

### CODE REVIEW

**Review by shwetha-manvinkurke — COMMENTED** [review]
@shamigor Would you be able to generate the [twilio-go](https://github.com/twilio/twilio-go) against the new changes and submit a PR there as well and link it to this one?

**Comment by shamigor** [comment]
> @shamigor Would you be able to generate the [twilio-go](https://github.com/twilio/twilio-go) against the new changes and submit a PR there as well and link it to this one?

Yes, done.  [PR](https://github.com/twilio/twilio-go/pull/82)
Only I'm not sure about the version  _* API version: 1.16.1_. Should I change the version?

**Review by childish-sambino — COMMENTED** [review]
Looks simple enough. Nice fix.

Think a unit test is needed as well. Since we already have an array-type property in the [test fixture](https://github.com/twilio/twilio-oai-generator/blob/931d872e19434ebbe6bdd6ec725a85a3c6a98c17/examples/go/oai.yaml#L840-L847), you could add a test which verifies calling the generated code properly sets the payload.

**Comment by shamigor** [comment]
> Looks simple enough. Nice fix.
> 
> Think a unit test is needed as well. Since we already have an array-type property in the [test fixture](https://github.com/twilio/twilio-oai-generator/blob/931d872e19434ebbe6bdd6ec725a85a3c6a98c17/examples/go/oai.yaml#L840-L847), you could add a test which verifies calling the generated code properly sets the payload.

Added. Could you check it please?

**Review by childish-sambino — APPROVED** [review]
🏅

**Pull request merged**
